backend/goodday/src/main/java/seeuthere/goodday/GooddayApplication.java, backend/goodday/src/main/java/seeuthere/goodday/group/domain/Group.java, backend/goodday/src/main/java/seeuthere/goodday/group/domain/History.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/Location.java, backend/goodday/src/main/java/seeuthere/goodday/member/domain/Guest.java, backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java, backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
<strong>
Closes #14 
</strong>
<br><br>
=> [3] 도메인 설계

frontend/src/pages/index.js
- 우분투 환경에서 빌드 실패하는 에러를 해결하였습니다.
```
export 'HomePage' (imported as 'HomePage') was not found in './pages' (module has no exports) @ ./src/index.js 3:0-28 5:160-163 
ERROR in ./src/pages/index.js 1:0-34 
Module not found: Error: Can't resolve './home' in '/var/jenkins_home/workspace/Frontend-ws/frontend/src/pages' resolve './home' in '/var/jenkins_home/workspace/Frontend-ws/frontend/src/pages' using description file: /var/jenkins_home/workspace/Frontend-ws/frontend/package.json (relative path: ./src/pages) Field 'browser' doesn't contain a valid alias configuration using description file: /var/jenkins_home/workspace/Frontend-ws/frontend/package.json (relative path: ./src/pages/home) no extension Field 'browser' doesn't contain a valid alias configuration …
```
=> fix: 대소문자 에러 수정

backend/goodday/src/main/java/seeuthere/goodday/location/controller/LocationController.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/CoordinateRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/LocationRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/Address.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/AxisDocument.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/AxisResponse.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/Meta.java, backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
- 도로명 주소 혹은 동 주소를 좌표로 전환해주는 기능 추가
<br><br>
- Refactoring LocationRequester 
<br><br>
- 1차적으로 주소를 받아서, 정확한 주소의 리스트를 보여주는 기능 
<br><br>
=> [3] 주소를 좌표로 전환해주는 기능

backend/goodday/src/main/java/seeuthere/goodday/location/controller/LocationController.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/CoordinateRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/LocationRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/Address.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/AxisDocument.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/AxisResponse.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/Meta.java, backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
<strong>
Closes #40
</strong>
- 해당 좌표를 기준으로 편의시설을 검색하는 기능을 추가했습니다.
- 키워드를 바탕으로 장소를 검색하는 기능을 추가했습니다.
<br><br>
- WebClient를 활용한 정보 요청시의 코드를 리팩토링했습니다.
<br><br>
- 중간 장소를 찾는 기능과 연결이 필요합니다.
<br><br>
=> [4] 좌표를 기준으로한 편의 시설 및 키워드 검색 기능

backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
- 트랜잭셔널 어노테이션을 붙여 실패하는 테스트 해결
<br><br>
```java
@ActiveProfiles("test")
````
요걸 추가해봤어요^-^
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
=> hotfix: 실패하는 테스트 수정

backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
- 배포 후 생기는 cors 문제해결 1차 시도
<br><br>
=> fix: strict origin cors 문제해결 시도 1

backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
=> fix: cors 문제 해결

backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
=> fix: 네이버 리다이렉트 URI 수정

backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
=> hotfix: 로그인 리다이렉트 링크 수정

backend/goodday/src/main/java/seeuthere/goodday/auth/domain/Kakao.java
<strong>
Closes #
</strong>
- 로그인에 관한 도메인 문제 해결
=> hotfix: 로그인 도메인 문제 해결

backend/goodday/src/main/java/seeuthere/goodday/auth/AuthenticationPrincipalConfig.java
<strong>
Closes #
</strong>
- 서버에서 cors 문제 해결
<br><br>
=> fix: 서버에서 cors 문제 해결

backend/goodday/src/docs/asciidoc/index.adoc
<strong>
Closes #74 
</strong>
- restdocs를 한 번에 모아볼 수 있는 index 페이지를 생성했습니다.
<br><br
- 추가적으로는 빌드 두 번을 해결할 수 있는 해결책이 필요합니다.
<br><br>
=> [4] feat: rest docs 목록 생성

backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/StationGrade.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/StationGrades.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/TimeGrade.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/MiddlePoint.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Point.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Points.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/Path.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/Paths.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/algorithm/Distance.java, backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java, backend/goodday/src/main/java/seeuthere/goodday/path/exception/PathExceptionSet.java
<strong>
Closes #98 
</strong>
- 최소시간 및 평균 시간을 고려한 알고리즘으로 수정하였습니다.
<br><br>
- 리팩토링 부분 추가
<br><br>
- PathService에 있는 로직을 도메인으로 내리게 리팩토링 
<br><br>
=> [6] 중간 경로 알고리즘 재산정 

frontend/src/pages/OAuth/index.js
- 로그인 시도할 경우, 프론트 코드 문제로 로그인이 진행되지 않는 문제가 있었습니다.
- 이를 해결하기 위한 코드를 추가했습니다.
- 스크린 샷: 로그인 시도 시 하얀 화면에서 멈춤
- 이 부분은 로컬 환경에서 테스트하기 어려워서, 저번 PR에 언급했던 것과 같이, 이번 hotfix 이후 다시 개발서버의 동작을 확인해봐야 할 것 같습니다.
<br><br>
=> fix: 로그인이 되지 않는 문제 해결

frontend/src/components/molecules/AuthRoute/index.js, frontend/src/contexts/UserContext.js, frontend/src/pages/Home/ParticipantAddForm.js, frontend/src/pages/Home/QuickAddModal.js, frontend/src/pages/OAuth/index.js, frontend/src/pages/Welcome/UserAddressAddForm.js
<strong>
Closes #
</strong>
- fix: 퍼블릭 페이지에서 계속 로그인을 Redirect되는 문제 해결
- fix: WelcomePage 주소제출 안되는 문제 해결
- refactor: 모달 이름 변경 EasyAdd -> QuickAdd
- style: 주석 제거
<br><br>
- 주소 닉네임 수정 useMutation 관련 버그 해결이 필요합니다.
<br><br>
=> fix: 로그인 페이지 및 웰컴 페이지 버그 해결

frontend/src/components/molecules/AuthRoute/index.js, frontend/src/components/molecules/NavBar/style.js, frontend/src/contexts/UserContext.js, frontend/src/pages/NotFound/index.js
- AuthRoute 카카오 로그인 문제 해결
- history 기능 동작 안하는 문제 해결 
- 로그아웃 버튼 패딩 삭제
=> [hotfix] AuthRoute 카카오 로그인 문제 해결

frontend/src/contexts/UserContext.js
<strong>
Closes #121
</strong>
- thanks to 멍토의 버그 제보
- 내 프로필 페이지에서 수정사항이 바로 반영되지 않는 문제를 해결하였습니다.
=> hotfix: 내 프로필 페이지에서 수정사항이 바로 반영되지 않는 문제 해결 v2.3.5

frontend/src/contexts/UserContext.js, frontend/src/hooks/useMutateProfile.js
<strong>
Closes #121
</strong>
- v2.3.5에서 해결되지 않은 문제를 해결했습니다.
<br><br>
=> hotfix: profile 수정사항 로컬 상태로 관리하도록 수정 v2.3.6

frontend/package.json, frontend/src/App.js, frontend/src/constants/api.js, frontend/src/contexts/UserContext.js
<strong>
Closes #125
</strong>
- 로그아웃 상태가 Navbar에 반영되지 않는 문제 해결
- 유저 상태가 초기화 되지 않아서 발생한 문제 => 유저 상태에서 토큰을 분리해서 따로 관리
<br><br>
=> [hotfix] 로그아웃 상태가 Navbar에 반영되지 않는 문제 해결 v2.3.7

backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
=> refactor: 알고리즘 복구

backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
- fix: cors dev 서버 추가
<br><br>
=> fix: cors dev 서버 추가

backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java, backend/goodday/src/main/resources/application-prod.yml, backend/goodday/src/main/resources/application-test.yml
=> Revert "feat: develop과 main 별로 url 다르게 설정 (#152)"

backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java, backend/goodday/src/main/resources/application-prod.yml, backend/goodday/src/main/resources/application-test.yml
- 영이랑 춘식 커밋 반영안된거 다시 반영했습니다. 
<br><br>
=> fix: 누락된 부분 수정

backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/dto/request/LocationRequest.java, backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java, backend/goodday/src/main/java/seeuthere/goodday/path/controller/PathController.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/Path.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/Paths.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/PointWithName.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/algorithm/Distance.java, backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java, backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/PathResponse.java, backend/goodday/src/main/java/seeuthere/goodday/path/service/PathService.java, backend/goodday/src/main/java/seeuthere/goodday/secret/SecretKey.java, backend/goodday/src/test/java/seeuthere/goodday/path/PathAcceptanceTest.java, backend/goodday/src/test/java/seeuthere/goodday/path/domain/PathTest.java, backend/goodday/src/test/java/seeuthere/goodday/path/domain/algorithm/DistanceTest.java
<strong>
Closes #162 
</strong>
Redis 캐싱방법 변경이 필요함.
<br><br>
=> [7] 알고리즘 개선 및 경로개선

backend/goodday/src/docs/asciidoc/member.adoc, backend/goodday/src/main/java/seeuthere/goodday/DataLoader.java, backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java, backend/goodday/src/main/java/seeuthere/goodday/member/dao/RequestFriendRepository.java, backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java, backend/goodday/src/main/java/seeuthere/goodday/member/domain/RequestFriend.java, backend/goodday/src/main/java/seeuthere/goodday/member/dto/RequestFriendRequest.java, backend/goodday/src/main/java/seeuthere/goodday/member/dto/RequestFriendResponse.java, backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java, backend/goodday/src/test/java/seeuthere/goodday/DataLoader.java, backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java, backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
<strong>
Closes #151 
</strong>
- 친구 요청 및 수락 
- 나한테 들어온 요청 목록 가져오기
- 내가 넣은 요청 목록 가져오기
- 친구 요청
- 요청 수락
- 요청 거절
- 요청 취소
<br><br>
=> [6] 친구 요청 및 수락

backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java, backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
- 친구 요청 및 요청 받은 목록 조회 api 주소 수정
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
=> [1] 친구 요청 및 요청 받은 목록 조회 api 주소 수정

backend/goodday/src/docs/asciidoc/list.adoc, backend/goodday/src/docs/asciidoc/member.adoc
메인서버 문서만 연결하는 것이 아니라 개발서버의 문서와 연동되도록 수정
<br><br>
=> [0.5] fix: 개발문서 위치 추가 및 경로 수정

backend/goodday/Jenkinsfile.groovy, backend/goodday/build.gradle, backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java, backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java, backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java, backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java, backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
#140 
- 소나큐브 적용
- 친구 검색시 모든 단어가 일치해야 검색 가능하도록 수정
<br><br>
=> [3] Sonarqube 적용

backend/goodday/src/main/java/seeuthere/goodday/location/config/WeightStationConfig.java
jar에서 파일을 못 읽어오는 버그 수정
<br><br>
리팩터링
<br><br>
=> [fix] 파일경로 수정

backend/goodday/Jenkinsfile.groovy, backend/goodday/build.gradle, backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java, backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java, backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java, backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java, backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
<strong>
Closes #140 
</strong>
- sonarqube 적용
<br><br>
=> [8] sonsarqube 적용

backend/goodday/build.gradle, backend/goodday/src/main/java/seeuthere/goodday/GooddayApplication.java
=> [1] aws error 안보이도록 수정

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/atoms/ProgressBar/index.js, frontend/src/components/atoms/ProgressBar/style.js, frontend/src/components/molecules/MidpointLoader/index.js, frontend/src/constants/style.js, frontend/src/contexts/MapViewContext.js, frontend/src/contexts/ParticipantContext.js, frontend/src/contexts/UserContext.js, frontend/src/hooks/useFriendSearch.js, frontend/src/hooks/useMapViewApi.js, frontend/src/hooks/useMutateFriend.js, frontend/src/hooks/useMutateProfile.js, frontend/src/pages/Friend/FriendSearchModal.js, frontend/src/pages/Midpoint/ParticipantChips.js, frontend/src/pages/Midpoint/PersonalPath.js, frontend/src/pages/Midpoint/index.js, frontend/src/pages/Midpoint/style.js
<strong>
Closes #174, Closes #175, Closes #187, Closes #188
</strong>
- 로그아웃해도 참석자 목록이 남아있는 문제를 해결했습니다.
- 이전에 조회한 중간지점이 새로운 경로에 남아있는 문제를 해결했습니다.
- 일치하는 ID 검색결과가 없을 때 UI 깨짐현상 해결했습니다.
- 내 프로필 페이지에서 중복 ID 변경 시도 관련 에러 처리 추가했습니다.
- 이미 친구인 경우 등 친구 수락 기능 관련 에러 처리 추가했습니다.
<br><br>
- 성능개선 관련, 중간지점 결과페이지 로딩이 더 매끄럽게 처리되도록 변경했습니다.
- 기타 UI 깨짐 현상을 수정했습니다. (공유하기 버튼, 결과페이지 ContentArea 배경색)
- 로딩속도가 긴 경우 UX를 고려해, 로딩바 애니메이션 최대시간을 4s에서 20s로 늘리고 애니메이션을 재구성했습니다.
- 공공 API 출처 표시가이드를 참고해 API 출처를 명시했습니다. 
<br><br>
- http://ccl.cckorea.org/reuse/source-display/
- https://www.data.go.kr/data/15000414/openapi.do
<br><br>
- 아래와 같은 함수를 여러 fetch 함수에서 이미 사용하고 있는데 문제는 없는지 다시 검토가 필요합니다.
- 정상적으로 동작한다면, 함수를 따로 빼서 중복 코드를 제거하는 것이 좋아보입니다.
```js
const httpRequestAuth = async (method, url, body) => {
const response = await …
```
=> [4] 프론트엔드 스프린트3 종합 버그픽스 v3.4.1

backend/goodday/src/main/java/seeuthere/goodday/location/dto/PathTransferResult.java, backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
<strong>
Closes #193 
</strong>
- 멀티스레드를 통해서 성능을 3배 상승시켰습니다. 
- 멀티쓰레드를 위한 스레드 안정성을 고려하였습니다.
<br><br>
- 멀티 스레드 추가할 공간 찾아보기
<br><br>
=> [8] 멀티 스레드 환경에서의 WebClient 크롤링 개선

backend/goodday/src/main/java/seeuthere/goodday/location/config/LocationRequestConfig.java, backend/goodday/src/main/java/seeuthere/goodday/location/config/Requesters.java, backend/goodday/src/main/java/seeuthere/goodday/location/config/WeightStationConfig.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/WeightStations.java, backend/goodday/src/main/java/seeuthere/goodday/location/exception/LocationExceptionSet.java, backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/TransportCache.java, backend/goodday/src/main/java/seeuthere/goodday/path/repository/SubwayRedisRepository.java, backend/goodday/src/main/java/seeuthere/goodday/path/service/PathService.java
- Bean 간결화를 위한 객체 Refactor
<br><br>
=> [1] Requesters refactor

.github/workflows/fe-tests.yml, README.md, backend/README.md, frontend/README.md
- 리드미를 작성했습니다!
<br><br>
- 프론트테스트 yml 파일에서 우분투 버전을 맞췄습니다. (20.04 -> 18.04)
<br><br>
=> docs: 리드미 업데이트

backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
유료 도메인에서 연결할 수 있도록 코드를 수정했습니다.
<br><br>
=> [1] 유료도메인 연결허용

backend/README.md, frontend/README.md
=> main develop 충돌 해결

backend/goodday/src/main/java/seeuthere/goodday/auth/exception/AuthExceptionSet.java, backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java, backend/goodday/src/main/java/seeuthere/goodday/auth/utils/NaverUtil.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/CoordinateRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/LocationRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/SearchRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java, backend/goodday/src/main/java/seeuthere/goodday/location/exception/LocationExceptionSet.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/requester/TransportRequester.java, backend/goodday/src/main/java/seeuthere/goodday/path/exception/PathExceptionSet.java
<strong>
Closes #205 
</strong>
WebClient 사용방법을 수정했습니다.
<br><br>
=> [2] WebClient 사용방법 수정

backend/goodday/.gitignore, backend/goodday/build.gradle, backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileResponse.java, backend/goodday/src/main/resources/db/migration/V1__init.sql
<strong>
Closes #144 
</strong>
- flyway 적용 완료
<br><br>
=> [6] flyway 적용 

backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
<strong>
Closes #217 
</strong>
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
=> [1]bugfix 경로 정보 찾기 버그 수정

backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/TransportCache.java, backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIItemListResponse.java, backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java, backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APITransportResponse.java
- 포맷팅하면서 final 이 붙어 생긴 충돌을 제거하여 해결
=> [0.5] fix: 포맷팅 후 충돌 해결

backend/goodday/build.gradle, backend/goodday/src/main/java/seeuthere/goodday/board/controller/BoardController.java, backend/goodday/src/main/java/seeuthere/goodday/board/dto/response/BoardResponse.java, backend/goodday/src/main/java/seeuthere/goodday/board/dto/response/CommentResponse.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/DuplicateStationRemover.java, backend/goodday/src/main/java/seeuthere/goodday/location/domain/combiner/AxisKeywordCombiner.java, backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
=> [0.2] refactor: major minor level code smell 일부 제거

backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java, backend/goodday/src/main/java/seeuthere/goodday/path/domain/Path.java
=> fix: 주소 생성 문제 해결

backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
<strong>
Closes #
</strong>
- address 생성관련 문제 해결
<br><br>
=> fix: address 생성문제 수정

backend/goodday/build.gradle
- `/api/docs/{path}` 안되는 이슈 해결
<br><br>
- yml에 mvc 부분 추가 필요
<br><br>
=> hotfix: api/docs 버그 관련 build.gradle 추가

backend/goodday/src/main/java/seeuthere/goodday/board/controller/BoardController.java, backend/goodday/src/main/java/seeuthere/goodday/board/dao/BoardRepository.java, backend/goodday/src/main/java/seeuthere/goodday/board/domain/BoardLabel.java, backend/goodday/src/main/java/seeuthere/goodday/board/service/BoardService.java, backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
<strong>
Closes #241 
</strong>
- Pagination 기능을 구현했습니다.
=> [2] 문의사항 Pagination 설정

backend/goodday/build.gradle, backend/goodday/src/main/java/seeuthere/goodday/GoodDayApplication.java, backend/goodday/src/main/java/seeuthere/goodday/auth/service/AuthService.java, backend/goodday/src/main/java/seeuthere/goodday/board/service/BoardService.java, backend/goodday/src/main/java/seeuthere/goodday/config/replication/DataSourceConfig.java, backend/goodday/src/main/java/seeuthere/goodday/config/replication/RoutingDataSource.java, backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
<strong>
Closes #210 
</strong>
- 테스트, 배포서버 DB 레플리케이션 적용
<br><br>
- (없다면 이 문항을 지워주세요.)
<br><br>
=> 배포서버 DB 레플리케이션 적용

.gitmodules
<strong>
Closes #230
</strong>
- 깃 서브 모듈을 도입하였습니다.
<br><br>
=> [3] yml 관리를 위한 git submodule 도입

backend/goodday/build.gradle
=> [0.5] build.gradle 수정 

backend/goodday/src/docs/asciidoc/board.adoc, backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
<strong>
Closes #247
</strong>
- 게시판 adoc 수정
<br><br>
=> [1] board adoc 수정

backend/goodday/src/main/java/seeuthere/goodday/board/controller/BoardController.java, backend/goodday/src/main/java/seeuthere/goodday/board/dao/BoardRepository.java, backend/goodday/src/main/java/seeuthere/goodday/board/domain/Board.java, backend/goodday/src/main/java/seeuthere/goodday/board/domain/BoardType.java, backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/BoardRequest.java, backend/goodday/src/main/java/seeuthere/goodday/board/dto/response/BoardResponse.java, backend/goodday/src/main/java/seeuthere/goodday/board/service/BoardService.java, backend/goodday/src/main/resources/db/migration/V3__altertable.sql, backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java, backend/goodday/src/test/java/seeuthere/goodday/board/domain/BoardTest.java
<strong>
Closes #244 
</strong>
- BoardLabel 을 Type 으로 변경
<br><br>
=> [1] BoardLabel to type 으로 변경

backend/goodday/src/main/java/seeuthere/goodday/config/replication/CircularList.java, backend/goodday/src/main/java/seeuthere/goodday/config/replication/DataSourceConfig.java, backend/goodday/src/main/java/seeuthere/goodday/config/replication/DatabaseProperty.java, backend/goodday/src/main/java/seeuthere/goodday/config/replication/RoutingDataSource.java, backend/goodday/src/main/java/seeuthere/goodday/config/replication/Slave.java, backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
@ConfigurationProperties 을 이용하면 yml과 일치하는 부분을 변수와 매핑시켜준다.
매핑을 할때 setter가 필요하다.
https://velog.io/@kingcjy/Spring-Boot-JPA-DB-Replication-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
=> [4] refactor: slave 여러개 등록 가능하도록 수정하기

backend/goodday/src/main/java/seeuthere/goodday/member/dao/AdminRepository.java, backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java, backend/goodday/src/main/java/seeuthere/goodday/member/dao/RequestFriendRepository.java, backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java, backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
=> [1] JPA 쿼리 수정

backend/goodday/src/main/java/seeuthere/goodday/secret/SecretKey.java
=> hotfix: SecretKey Value 수정

backend/goodday/src/main/java/seeuthere/goodday/ControllerAdvice.java, backend/goodday/src/main/java/seeuthere/goodday/config/converter/AbstractCryptoConverter.java, backend/goodday/src/main/java/seeuthere/goodday/config/converter/ConverterException.java, backend/goodday/src/main/java/seeuthere/goodday/config/converter/CryptoDoubleConverter.java, backend/goodday/src/main/java/seeuthere/goodday/config/converter/CryptoStringConverter.java, backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java, backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
null 처리
log 기능 업데이트
pk 자동 생성 전략 변경
=> fix: null처리 기능 추가
